Repository FC-InnerCircle/icd01-team02-o2o2-fe, pull requests merged in 2024-08, with the labels that each got.

#2 기능별 페이지 및 routes 생성
  package-lock.json
  package.json
  src/App.tsx
  src/constants/common.ts
  src/main.tsx
  src/pages/Home.tsx
  src/pages/Menu.tsx
  src/pages/MenuDetail.tsx
  src/pages/Order.tsx
  src/pages/OrderDetail.tsx
  src/pages/Profile.tsx
  src/pages/Reviews.tsx
  src/pages/SignIn.tsx
  vite.config.ts
Labels: feature

#5 디자인에 맞춰 컬러 팔레트 및 폰트 정의 추가
  src/styles/color.ts
  src/styles/font.ts
Labels: enhancement

#10 User의 Role에 따른 page 접근 제한 기능 개발
  README.md
  src/App.tsx
  src/atoms/authAtom.ts
  src/atoms/sample.ts
  src/constants/common.ts
  src/pages/Home.tsx
  src/pages/Store.tsx
  src/pages/StoreDetail.tsx
  src/pages/User.tsx
  src/pages/UserDetail.tsx
  src/routes/AppRoutes.tsx
  src/routes/WithAuth.tsx
Labels: documentation, enhancement

#8 API 구현 및 hooks 구현, 타입 정의
  .husky/commit-msg
  .husky/pre-commit
  package-lock.json
  package.json
  src/api/core/index.ts
  src/api/index.ts
  src/api/instance/index.ts
  src/api/modules/account/index.ts
  src/api/modules/account/types.ts
  src/api/modules/auth/index.ts
  src/api/modules/auth/types.ts
  src/api/modules/commonType.ts
  src/api/modules/stores/index.ts
  src/api/modules/stores/types.ts
  src/main.tsx
  src/queries/keys/index.ts
  src/queries/modules/account/useAccountQuery.ts
  src/queries/modules/auth/useAuthQuery.ts
  src/queries/modules/managers/useManagersQuery.ts
  src/queries/modules/stores/useStoresQuery.ts
  tsconfig.json
Labels: feature

#17 test: msw 셋업, vitest 셋업
  src/mocks/handler.ts
  src/mocks/server.ts
  src/tests/test-utils.tsx
  vitest.config.ts
  vitest.setup.ts
Labels: enhancement

#20 Layout 디자인 완료
  commitlint.config.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/layout/index.tsx
  src/components/common/menus/index.tsx
  src/components/icons/assets/dashboard.svg
  src/components/icons/assets/menus.svg
  src/components/icons/assets/order.svg
  src/components/icons/assets/review.svg
  src/components/icons/assets/search.svg
  src/components/icons/index.ts
  src/main.tsx
  src/styles/color.ts
  src/styles/font.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: enhancement, feature
