Repository FC-InnerCircle/icd01-team02-o2o2-fe, pull requests merged in 2024-09, with the labels that each got.

#19 로그인 페이지 구현
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/core/index.ts
  src/api/modules/account/index.ts
  src/assets/login.jpg
  src/constants/common.ts
  src/env.d.ts
  src/main.tsx
  src/mocks/__fixtures__/accounts.ts
  src/mocks/__fixtures__/auth.ts
  src/mocks/__fixtures__/index.ts
  src/mocks/__fixtures__/menu.ts
  src/mocks/__fixtures__/orders.ts
  src/mocks/__fixtures__/reviews.ts
  src/mocks/__fixtures__/stores.ts
  src/mocks/core/browser.ts
  src/mocks/core/server.ts
  src/mocks/handler.ts
  src/mocks/handlers.ts
  src/pages/SignIn.tsx
  src/pages/Signin/SignIn.test.tsx
  src/pages/Signin/index.tsx
  src/queries/core/index.ts
  src/queries/modules/account/useAccountQuery.ts
  src/queries/modules/stores/useStoresQuery.ts
  src/routes/AppRoutes.tsx
  src/schema/index.ts
  tsconfig.json
  vitest.setup.ts
Labels: feature

#23 메뉴 등록 페이지 UI 구현
  package-lock.json
  package.json
  src/components/common/LabelInput/LabelInput.types.ts
  src/components/common/LabelInput/index.tsx
  src/components/common/LabelTextarea/LabelTextarea.types.ts
  src/components/common/LabelTextarea/index.tsx
  src/components/common/layout/index.tsx
  src/components/common/menus/index.tsx
  src/components/icons/assets/edit.svg
  src/components/icons/assets/trash.svg
  src/components/icons/index.ts
  src/components/menu/MenuOption/index.tsx
  src/components/menu/index.ts
  src/constants/common.ts
  src/hooks/useClickOutside.ts
  src/pages/MenuRegistration.tsx
  src/routes/AppRoutes.tsx
  src/styles/color.ts
  src/styles/font.ts
Labels: enhancement, feature

#38 option modal 구현
  src/api/modules/menu/types.ts
  src/api/modules/stores/index.ts
  src/api/modules/stores/types.ts
  src/common/components/button/Button.tsx
  src/common/components/icons/assets/plus.svg
  src/common/components/icons/index.ts
  src/common/components/layout/index.tsx
  src/common/components/layout/menus/index.tsx
  src/pages/menu/components/index.ts
  src/pages/menu/components/labelInput/LabelInput.types.ts
  src/pages/menu/components/labelInput/index.tsx
  src/pages/menu/components/labelTextarea/LabelTextarea.types.ts
  src/pages/menu/components/labelTextarea/index.tsx
  src/pages/menu/components/menuOption/index.tsx
  src/pages/menu/components/menuOption/index.types.ts
  src/pages/menu/components/onOffButton/index.tsx
  src/pages/menu/components/onOffButton/types.ts
  src/pages/menu/components/optionItemInput/index.tsx
  src/pages/menu/components/optionItemInput/types.ts
  src/pages/menu/components/optionModal/index.tsx
  src/pages/menu/components/optionModal/types.ts
  src/pages/menu/constants/index.ts
  src/pages/menu/detail.tsx
  src/pages/menu/hooks/useCreateMenu/index.tsx
  src/pages/menu/registration.tsx
  src/pages/menuDetail/components/index.ts
  src/pages/menuList/index.tsx
  src/pages/menuRegistration/index.tsx
  src/queries/modules/stores/useStoresQuery.ts
  src/routes/AppRoutes.tsx
Labels: feature

#44 menu 상세 정보 조회 및 수정 UI 구현
  src/api/modules/menu/types.ts
  src/api/modules/stores/types.ts
  src/assets/americano.webp
  src/pages/menu/detail.tsx
  src/pages/menu/hooks/useMenuDetail/index.tsx
  src/pages/menu/hooks/useMenuOption/index.tsx
Labels: feature

#45 메뉴 리스트 UI 구현
  src/assets/cappuccino.webp
  src/assets/caramel.webp
  src/assets/chailatte.webp
  src/assets/espresso.webp
  src/assets/hotamericano.webp
  src/assets/hotchoco.webp
  src/assets/iceamericano.webp
  src/assets/latte.webp
  src/assets/matcha.webp
  src/assets/mocha.webp
  src/assets/vanila.webp
  src/pages/menuList/components/menuCard/index.tsx
  src/pages/menuList/components/menuCard/types.ts
  src/pages/menuList/index.tsx
  src/pages/menuList/types.ts
Labels: feature

#47 merge되면서 menu 등록 파일 루트 수정, 간격 맞추기, routing 수정
  src/common/components/layout/menus/index.tsx
  src/pages/dashboard/OwnerHome.tsx
  src/pages/dashboard/components/CardList.tsx
  src/pages/dashboard/components/OrderTable.tsx
  src/pages/menu/detail.tsx
  src/pages/menuList/index.tsx
  src/pages/menuRegistration/index.tsx
  src/routes/AppRoutes.tsx
Labels: bug, enhancement
